// Note: This is a dummy data created based on the documents, it's not taken from a real device
// Maybe someone can provide the real data for this device.
export const glacierProperties = {
  code: "0" as const,
  message: "Success" as const,
  data: {
    "bms_bmsStatus.amp": 20,
    "bms_bmsStatus.bmsFault": 20,
    "bms_bmsStatus.bqStatReg": 20,
    "bms_bmsStatus.cellId": 20,
    "bms_bmsStatus.designCap": 20,
    "bms_bmsStatus.err": 20,
    "bms_bmsStatus.f32ShowSoc": 10.1,
    "bms_bmsStatus.fullCap": 20,
    "bms_bmsStatus.inWatts": 20,
    "bms_bmsStatus.maxCellTmp": 20,
    "bms_bmsStatus.maxCellVol": 20,
    "bms_bmsStatus.maxMosTmp": 20,
    "bms_bmsStatus.minCellTmp": 20,
    "bms_bmsStatus.minCellVol": 20,
    "bms_bmsStatus.minMosTmp": 20,
    "bms_bmsStatus.num": 2,
    "bms_bmsStatus.openBmsIdx": 0,
    "bms_bmsStatus.outWatts": 20,
    "bms_bmsStatus.remainCap": 20,
    "bms_bmsStatus.remainTime": 20,
    "bms_bmsStatus.soc": 20,
    "bms_bmsStatus.soh": 20,
    "bms_bmsStatus.tagChgAmp": 20,
    "bms_bmsStatus.tmp": 20,
    "bms_bmsStatus.type": 2,
    "bms_bmsStatus.ver": 20,
    "bms_bmsStatus.vol": 20,
    "bms_emsStatus.bmsIsConnt": 20,
    "bms_emsStatus.bmsModel": 20,
    "bms_emsStatus.chgCmd": 20,
    "bms_emsStatus.chgRemain": 20,
    "bms_emsStatus.chgVol": 20,
    "bms_emsStatus.closeOilEbSocMax": 20,
    "bms_emsStatus.dsgCmd": 20,
    "bms_emsStatus.dsgRemain": 20,
    "bms_emsStatus.emsFlag": 0,
    "bms_emsStatus.fanLvl": 20,
    "bms_emsStatus.lcdSoc": 20,
    "bms_emsStatus.maxAvailNum": 20,
    "bms_emsStatus.maxChgSoc": 20,
    "bms_emsStatus.minDsgSoc": 20,
    "bms_emsStatus.openBmsIdx": 20,
    "bms_emsStatus.openOilEbSocMin": 20,
    "bms_emsStatus.paraVolMax": 20,
    "bms_emsStatus.paraVolMin": 20,
    "bms_emsStatus.upsFlag": 20,
    "bms_emsStatus.warnState": 20,
    "pd.A12Val": 20,
    "pd.ambientTmp": 20,
    "pd.appOpCountBeepOff": 20,
    "pd.appOpCountBeepOn": 20,
    "pd.appOpCountBlTime": [1, 2, 3],
    "pd.appOpCountDeIce": 20,
    "pd.appOpCountDntMakeIce": 20,
    "pd.appOpCountPowerOff": 20,
    "pd.appOpCountPowerOn": 20,
    "pd.appOpCountTempUnitC": 20,
    "pd.appOpCountTempUnitF": 20,
    "pd.appOpCountWorkMode": [1, 2, 3],
    "pd.appOpTimeBlTime": [1, 2, 3],
    "pd.appSensorAdv": [1, 2, 3],
    "pd.batFlag": 1,
    "pd.batPct": 20,
    "pd.batTime": 20,
    "pd.beepEn": 1,
    "pd.blTime": 20,
    "pd.bldcDntIce": 1,
    "pd.bldcDntWork": 1,
    "pd.bmsInFlag": 20,
    "pd.buttonLong": [1, 2, 3],
    "pd.buttonShort": [1, 2, 3],
    "pd.carBatLow": 1,
    "pd.chargeWorkCount": 20,
    "pd.chargeWorkTime": 20,
    "pd.chargeXt60Count": [1, 2, 3],
    "pd.chargeXt60Time": [1, 2, 3],
    "pd.chgType": 6,
    "pd.coolCoverCount": 20,
    "pd.coolCoverTime": 20,
    "pd.coolMode": 1,
    "pd.coolZoneDoubleCount": 20,
    "pd.coolZoneDoubleTime": 20,
    "pd.coolZoneSingleCount": 20,
    "pd.coolZoneSingleTime": 20,
    "pd.countinueMakeIceAve": 20,
    "pd.countinueMakeIceMax": 20,
    "pd.dntMakeIceDevice": 20,
    "pd.doorStat": 1,
    "pd.emsChgFlg": 20,
    "pd.err": 20,
    "pd.errBldc": 20,
    "pd.errBms": 20,
    "pd.errCode": 20,
    "pd.errLcd": 20,
    "pd.errPd": 20,
    "pd.errPwr": 20,
    "pd.errorCountBldc": [1, 2, 3],
    "pd.errorCountBms": [1, 2, 3],
    "pd.errorCountPd": [1, 2, 3],
    "pd.errorCountPower": [1, 2, 3],
    "pd.errorTimeBms": [1, 2, 3],
    "pd.errorTimePd": [1, 2, 3],
    "pd.errorTimePower": [1, 2, 3],
    "pd.exhaustTmp": 20,
    "pd.fanLvl": 20,
    "pd.flagAmbintReady": 1,
    "pd.flagTwoZone": 20,
    "pd.fsmState": 20,
    "pd.iceAlert": 1,
    "pd.iceMkMode": 3,
    "pd.icePercent": 20,
    "pd.iceTm": 20,
    "pd.iceTmTag": 20,
    "pd.makeIceCount": 20,
    "pd.motorCur": 20,
    "pd.motorSpeed": 20,
    "pd.motorVol": 20,
    "pd.motorWait": 1,
    "pd.motorWat": 20,
    "pd.networkTypeCount": [1, 2, 3],
    "pd.networkTypeTime": [1, 2, 3],
    "pd.powerBatInCount": 20,
    "pd.powerBatInTime": 20,
    "pd.powerBatOutTime": 20,
    "pd.powerPbLevel": 20,
    "pd.powerXt60Count": [1, 2, 3],
    "pd.powerXt60Time": [1, 2, 3],
    "pd.pwrPbEn": 20,
    "pd.pwrState": 20,
    "pd.resvB": [1, 2, 3],
    "pd.resvD": [1, 2, 3],
    "pd.resvP": [1, 2, 3],
    "pd.runState": 2,
    "pd.sensor": 20,
    "pd.sensorAdv": 20,
    "pd.tempAmbientTime": [1, 2, 3],
    "pd.tempCoolSetTime": [1, 2, 3],
    "pd.tempCoolTime": [1, 2, 3],
    "pd.tempIceTime": [1, 2, 3],
    "pd.tempWater": 20,
    "pd.threeWayState": 20,
    "pd.tmpAver": 20,
    "pd.tmpL": 20,
    "pd.tmpLSet": 20,
    "pd.tmpMSet": 20,
    "pd.tmpR": 20,
    "pd.tmpRSet": 20,
    "pd.tmpUnit": 0,
    "pd.warnInfo": 20,
    "pd.waterLine": 20,
    "pd.workFsmCount": [1, 2, 3],
    "pd.workFsmTime": [1, 2, 3],
    "pd.workModeCount": 20,
    "pd.workModeTime": [1, 2, 3],
    "pd.xt150InState": 1,
    "pd.xt60InState": 1,
  },
};
