export const smartPlugProperties = {
  "2_1.brightness": 511,
  "2_1.country": 17477,
  "2_1.current": 860,
  "2_1.errCode": 0,
  "2_1.freq": 50,
  "2_1.maxCur": 0,
  "2_1.switchSta": false,
  "2_1.temp": 32,
  "2_1.town": 0,
  "2_1.updateTime": "2024-07-02 04:11:30",
  "2_1.volt": 228,
  "2_1.warnCode": 0,
  "2_1.watts": 10,
  "2_2.task1": {
    taskIndex: 0,
    type: 0,
    timeRange: {
      isConfig: false,
      timeData: 0,
      timeMode: 0,
      startTime: {
        sec: 0,
        week: 0,
        min: 0,
        hour: 0,
        month: 0,
        year: 0,
        day: 0,
      },
      stopTime: {
        sec: 0,
        week: 0,
        min: 0,
        hour: 0,
        month: 0,
        year: 0,
        day: 0,
      },
    },
  },
  "2_2.task2": {
    taskIndex: 1,
    type: 0,
    timeRange: {
      isConfig: false,
      timeData: 0,
      timeMode: 0,
      startTime: {
        sec: 0,
        week: 0,
        min: 0,
        hour: 0,
        month: 0,
        year: 0,
        day: 0,
      },
      stopTime: {
        sec: 0,
        week: 0,
        min: 0,
        hour: 0,
        month: 0,
        year: 0,
        day: 0,
      },
    },
  },
  "2_2.task3": {
    taskIndex: 2,
    type: 0,
    timeRange: {
      isConfig: false,
      timeData: 0,
      timeMode: 0,
      startTime: {
        sec: 0,
        week: 0,
        min: 0,
        hour: 0,
        month: 0,
        year: 0,
        day: 0,
      },
      stopTime: {
        sec: 0,
        week: 0,
        min: 0,
        hour: 0,
        month: 0,
        year: 0,
        day: 0,
      },
    },
  },
  "2_2.task4": {
    taskIndex: 3,
    type: 0,
    timeRange: {
      isConfig: false,
      timeData: 0,
      timeMode: 0,
      startTime: {
        sec: 0,
        week: 0,
        min: 0,
        hour: 0,
        month: 0,
        year: 0,
        day: 0,
      },
      stopTime: {
        sec: 0,
        week: 0,
        min: 0,
        hour: 0,
        month: 0,
        year: 0,
        day: 0,
      },
    },
  },
  "2_2.task5": {
    taskIndex: 4,
    type: 0,
    timeRange: {
      isConfig: false,
      timeData: 0,
      timeMode: 0,
      startTime: {
        sec: 0,
        week: 0,
        min: 0,
        hour: 0,
        month: 0,
        year: 0,
        day: 0,
      },
      stopTime: {
        sec: 0,
        week: 0,
        min: 0,
        hour: 0,
        month: 0,
        year: 0,
        day: 0,
      },
    },
  },
  "2_2.task6": {
    taskIndex: 5,
    type: 0,
    timeRange: {
      isConfig: false,
      timeData: 0,
      timeMode: 0,
      startTime: {
        sec: 0,
        week: 0,
        min: 0,
        hour: 0,
        month: 0,
        year: 0,
        day: 0,
      },
      stopTime: {
        sec: 0,
        week: 0,
        min: 0,
        hour: 0,
        month: 0,
        year: 0,
        day: 0,
      },
    },
  },
  "2_2.task7": {
    taskIndex: 6,
    type: 0,
    timeRange: {
      isConfig: false,
      timeData: 0,
      timeMode: 0,
      startTime: {
        sec: 0,
        week: 0,
        min: 0,
        hour: 0,
        month: 0,
        year: 0,
        day: 0,
      },
      stopTime: {
        sec: 0,
        week: 0,
        min: 0,
        hour: 0,
        month: 0,
        year: 0,
        day: 0,
      },
    },
  },
  "2_2.task8": {
    taskIndex: 7,
    type: 0,
    timeRange: {
      isConfig: false,
      timeData: 0,
      timeMode: 0,
      startTime: {
        sec: 0,
        week: 0,
        min: 0,
        hour: 0,
        month: 0,
        year: 0,
        day: 0,
      },
      stopTime: {
        sec: 0,
        week: 0,
        min: 0,
        hour: 0,
        month: 0,
        year: 0,
        day: 0,
      },
    },
  },
  "2_2.task9": {
    taskIndex: 8,
    type: 0,
    timeRange: {
      isConfig: false,
      timeData: 0,
      timeMode: 0,
      startTime: {
        sec: 0,
        week: 0,
        min: 0,
        hour: 0,
        month: 0,
        year: 0,
        day: 0,
      },
      stopTime: {
        sec: 0,
        week: 0,
        min: 0,
        hour: 0,
        month: 0,
        year: 0,
        day: 0,
      },
    },
  },
  "2_2.task10": {
    taskIndex: 9,
    type: 0,
    timeRange: {
      isConfig: false,
      timeData: 0,
      timeMode: 0,
      startTime: {
        sec: 0,
        week: 0,
        min: 0,
        hour: 0,
        month: 0,
        year: 0,
        day: 0,
      },
      stopTime: {
        sec: 0,
        week: 0,
        min: 0,
        hour: 0,
        month: 0,
        year: 0,
        day: 0,
      },
    },
  },
  "2_2.task11": {
    taskIndex: 10,
    type: 0,
    timeRange: {
      isConfig: false,
      timeData: 0,
      timeMode: 0,
      startTime: {
        sec: 0,
        week: 0,
        min: 0,
        hour: 0,
        month: 0,
        year: 0,
        day: 0,
      },
      stopTime: {
        sec: 0,
        week: 0,
        min: 0,
        hour: 0,
        month: 0,
        year: 0,
        day: 0,
      },
    },
  },
  "2_1.consNum": 4,
  "2_1.consWatt": -820,
  "2_1.geneNum": 1,
  "2_1.geneWatt": 8,
  "2_1.heartbeatFrequency": 15,
  "2_1.lanState": 4,
  "2_1.matterFabric": 2,
  "2_1.maxWatts": 2500,
  "2_1.meshEnable": 0,
  "2_1.meshId": 12234,
  "2_1.meshLayel": 1,
  "2_1.mqttErr": 6,
  "2_1.mqttErrTime": 1718773964,
  "2_1.otaDlErr": 0,
  "2_1.otaDlTlsErr": 0,
  "2_1.parentMac": 123442,
  "2_1.parentWifiRssi": -43,
  "2_1.resetCount": 9,
  "2_1.resetReason": 1,
  "2_1.rtcResetReason": 1,
  "2_1.runTime": 2480656,
  "2_1.selfEmsSwitch": 1,
  "2_1.selfMac": 1232424,
  "2_1.staIpAddr": -31324232,
  "2_1.stackFree": 64,
  "2_1.stackMinFree": 18,
  "2_1.wifiErr": 26,
  "2_1.wifiErrTime": 1718773747,
  "2_2.updateTime": "2024-06-19 13:13:09",
};
