name: PR Checks

on:
  pull_request:

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Setup Node.js 24
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '24.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
